name: JFiddle - Fiddler Extraordinaire
favicon: null
layout_spectrum: 0.2973065066616982
typography_spectrum: 0.6725765538867563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8018369099590927
  lightness: 0.10215614945627749
  saturation: 0.670444248476997
  rhythmicContrast: 0.9909083771053702
purpose: []
